import type { NextPage } from 'next'
import Head from 'next/head'
import '../styles/Home.module.css'
import SiteHeader from '../components/Header'
import SiteFooter from "../components/Footer";
import Landing from "../components/Landing";
import SiteCalendar from "../components/Calendar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SiteHeader links={[{link:'/about',label:'About'}, {link:'/calendar',label:'events'}]}/>
        <Landing/>
        <SiteCalendar/>
      </main>
      <div className="text-center">
        <SiteFooter/>
      </div>
      
    </div>
  )
}

export default Home
